name: Quant Guardian Ultra

on:
  schedule:
    # 台灣時間 UTC+8
    # 06:00 美股盤後
    - cron: "0 22 * * *"
    # 08:00 台股盤前
    - cron: "0 0 * * *"
    # 14:30 台股盤後
    - cron: "30 6 * * *"
    # 20:00 美股盤前
    - cron: "0 12 * * *"

  workflow_dispatch:

jobs:
  run-guardian:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Quant Guardian
        env:
          DISCORD_TW_STOCK: ${{ secrets.DISCORD_TW_STOCK }}
          DISCORD_US_STOCK: ${{ secrets.DISCORD_US_STOCK }}
          DISCORD_BLACK_SWAN: ${{ secrets.DISCORD_BLACK_SWAN }}
          DISCORD_GENERAL_NEWS: ${{ secrets.DISCORD_GENERAL_NEWS }}
        run: |
          python entrypoint.py
