name: Local Vault Cleanup
on:
  schedule:
    - cron: "30 23 * * *"
  workflow_dispatch:

jobs:
  vault-clean:
    runs-on: self-hosted
    steps:
      - name: Run vault cleanup
        shell: powershell
        run: |
          python vault/run_vault_cleanup.py
